version: "1.0.1"
name: "mongo-compose"

services:
  mongo-be-compose:
    container_name: "mongo-be-compose"
    depends_on:
      - mongo-db-compose
    build:
      dockerfile: "Dockerfile"
      context: .
      target: deps
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=$MONGO_URI
    ports:
      - "8000:8000"
    networks:
      - compose_mern_network
    restart: always
    command: npm run start

  mongo-db-compose:
    container_name: "mongo-db-compose"
    image: mongo
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_ROOT_DB=$MONGO_DB
    ports:
      - ${MONGO_LOCAL_PORT}:${MONGO_DOCKER_PORT}
    networks:
      - compose_mern_network

networks:
  compose_mern_network:
    external: true
